In [33]:
import pandas as pd 
import matplotlib.pyplot as plt

In [34]:
data = pd.read_csv('../updatedtop20datasets/AAPL.csv')
data.head(5)

         Date     close      high       low      open      volume Symbol
0  2008-01-02  5.832620  5.994870  5.764068  5.965234  1079178800   AAPL
1  2008-01-03  5.835313  5.908954  5.768258  5.849682   842066400   AAPL
2  2008-01-04  5.389873  5.777537  5.355148  5.731137  1455832000   AAPL
3  2008-01-07  5.317728  5.496143  5.095906  5.425794  2072193200   AAPL
4  2008-01-08  5.126441  5.462018  5.112970  5.392567  1523816000   AAPL

In [35]:
### Creating the different rows and columns
### 1. Did the price go up or down today 
def featuers_creation(data):
    data['return'] = data['close'].diff()/ data['close'].shift(1)
    data['return'] = data['return'].fillna(0)
    data['Volatility_7Days'] = data['close'].rolling(window = 7).std()
    data['Volatility_7Days'] = data['Volatility_7Days'].fillna(0)
    data['Volatility_30Days'] = data['close'].rolling(window = 30).std()
    data['Volatility_30Days'] = data['Volatility_30Days'].fillna(0)
    return data

### What is rolling Volatility ?!
### Rolling Volatility measures how much a stock's price has been (moving up and down ) over a fixed window of a time.

In [36]:
featuers_creation(data)

,Date,close,high,low,open,volume,Symbol,return,Volatility_7Days,Volatility_30Days
0,2008-01-02,5.832620,5.994870,5.764068,5.965234,1079178800,AAPL,0.000000,0.000000,0.000000
1,2008-01-03,5.835313,5.908954,5.768258,5.849682,842066400,AAPL,0.000462,0.000000,0.000000
2,2008-01-04,5.389873,5.777537,5.355148,5.731137,1455832000,AAPL,-0.076335,0.000000,0.000000
3,2008-01-07,5.317728,5.496143,5.095906,5.425794,2072193200,AAPL,-0.013385,0.000000,0.000000
4,2008-01-08,5.126441,5.462018,5.112970,5.392567,1523816000,AAPL,-0.035971,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...
4623,2026-05-19,298.970001,300.510010,296.350006,296.970001,42243600,AAPL,0.003794,2.661993,14.162720
4624,2026-05-20,302.250000,302.799988,298.079987,298.179993,38229800,AAPL,0.010971,2.281251,14.414926
4625,2026-05-21,304.989990,305.540009,300.399994,301.059998,42965100,AAPL,0.009065,2.580657,14.741897
4626,2026-05-22,308.820007,311.399994,305.839996,306.119995,43627900,AAPL,0.012558,4.051026,15.128236
4627,2026-05-26,309.230011,311.820007,309.065002,309.399994,21968009,AAPL,0.001328,4.609677,15.283562