In [89]:
import pandas as pd 
import matplotlib.pyplot as plt

In [90]:
data = pd.read_csv('../updatedtop20datasets/AAPL.csv')
data.head(5)

         Date     close      high       low      open      volume Symbol
0  2008-01-02  5.832620  5.994870  5.764068  5.965234  1079178800   AAPL
1  2008-01-03  5.835313  5.908954  5.768258  5.849682   842066400   AAPL
2  2008-01-04  5.389873  5.777537  5.355148  5.731137  1455832000   AAPL
3  2008-01-07  5.317728  5.496143  5.095906  5.425794  2072193200   AAPL
4  2008-01-08  5.126441  5.462018  5.112970  5.392567  1523816000   AAPL

In [91]:
print(data.dtypes)

Date       object
close     float64
high      float64
low       float64
open      float64
volume      int64
Symbol     object
dtype: object

In [94]:
### Creating the different rows and columns
### 1. Did the price go up or down today 
def featuers_creation(data):
    data['return'] = data['close'].diff()/ data['close'].shift(1)
    data['return'] = data['return'].fillna(0)
    data['Volatility_7Days'] = data['close'].rolling(window = 7).std()
    data['Volatility_7Days'] = data['Volatility_7Days'].fillna(0)
    data['Volatility_30Days'] = data['close'].rolling(window = 30).std()
    data['Volatility_30Days'] = data['Volatility_30Days'].fillna(0)
    ## Price swing between the highest and lowest each day 
    data['Price_swing'] = (data['high'] - data['low']) / data['close']
    data['volume_zscore7Days'] = (data['volume'] - data['volume'].rolling(window = 7).mean())/ data['volume'].rolling(window = 7).std()
    data['volume_zscore7Days'] = data['volume_zscore7Days'].fillna(0)
    data['volume_zscore30Days'] = (data['volume'] - data['volume'].rolling(window = 30).mean())/ data['volume'].rolling(window = 30).std()
    data['volume_zscore30Days'] = data['volume_zscore30Days'].fillna(0)
    data['7Day'] = data['close'].rolling(window = 7).mean()
    data['30Day'] = data['close'].rolling(window = 30).mean()
    data['MASignal'] =( data['7Day'] > data['30Day']).astype(int)
    data = data.drop(columns=['7Day', '30Day'])
    return data

### What is rolling Volatility ?!
### Rolling Volatility measures how much a stock's price has been (moving up and down ) over a fixed window of a time. 
### Here we have taken 7 days and 30 days which means how volatile the stock was in the given window of time

---
### Price swing! 
### Price swing also helps to identify how volatile was the stock during the given day

---
### Volume z score 
### The volume z score helps calculate how suprising is today's activity in terms of volume or total stocks traded. Rolling window of 7 days and 30 days allows us to calculate how weird was the stock in the span of 7 or 30 days

In [95]:
featuers_creation(data)

,Date,close,high,low,open,volume,Symbol,return,Volatility_7Days,Volatility_30Days,Price_swing,volume_zscore7Days,volume_zscore30Days,MASignal
0,2008-01-02,5.832620,5.994870,5.764068,5.965234,1079178800,AAPL,0.000000,0.000000,0.000000,0.039571,0.000000,0.000000,0
1,2008-01-03,5.835313,5.908954,5.768258,5.849682,842066400,AAPL,0.000462,0.000000,0.000000,0.024111,0.000000,0.000000,0
2,2008-01-04,5.389873,5.777537,5.355148,5.731137,1455832000,AAPL,-0.076335,0.000000,0.000000,0.078367,0.000000,0.000000,0
3,2008-01-07,5.317728,5.496143,5.095906,5.425794,2072193200,AAPL,-0.013385,0.000000,0.000000,0.075265,0.000000,0.000000,0
4,2008-01-08,5.126441,5.462018,5.112970,5.392567,1523816000,AAPL,-0.035971,0.000000,0.000000,0.068088,0.000000,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4623,2026-05-19,298.970001,300.510010,296.350006,296.970001,42243600,AAPL,0.003794,2.661993,14.162720,0.013914,-0.216737,-0.285474,1
4624,2026-05-20,302.250000,302.799988,298.079987,298.179993,38229800,AAPL,0.010971,2.281251,14.414926,0.015616,-0.632566,-0.570177,1
4625,2026-05-21,304.989990,305.540009,300.399994,301.059998,42965100,AAPL,0.009065,2.580657,14.741897,0.016853,-0.000670,-0.269186,1
4626,2026-05-22,308.820007,311.399994,305.839996,306.119995,43627900,AAPL,0.012558,4.051026,15.128236,0.018004,0.283785,-0.256069,1
4627,2026-05-26,309.230011,311.820007,309.065002,309.399994,21968009,AAPL,0.001328,4.609677,15.283562,0.008909,-1.770876,-1.793996,1