In [252]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest

### We will be using isolation forest to detect the anamolies

In [253]:
data = pd.read_parquet('../updatedtop20datasets/META.parquet')
data.head(5)

                       date    close  ...  cum_score  is_anomaly
0 2012-05-18 00:00:00+00:00  38.2318  ...   0.061616           0
1 2012-05-21 00:00:00+00:00  34.0300  ...   0.049181           1
2 2012-05-22 00:00:00+00:00  31.0000  ...   0.060762           0
3 2012-05-23 00:00:00+00:00  32.0000  ...   0.135995           0
4 2012-05-24 00:00:00+00:00  33.0300  ...   0.125875           0

[5 rows x 29 columns]

In [254]:
def data_partition(symbol):
    path = '../updatedtop20datasets/'
    filepath = f'{path}{symbol}.parquet'
    columns =  ['price_return', 'volatility_diff', 'Volatility_30Days', 'Price_Swing', 'volume_z_diff', 'volume_zscore30Days','MASignal']
    data = pd.read_parquet(filepath)
    scaler = StandardScaler()
    data[columns] = scaler.fit_transform(data[columns])
    data.to_parquet(filepath, index = False)
    return data

In [255]:
def iso_runner(symbol,contamination = 0.05):
    path = '../updatedtop20datasets/'
    filepath = f'{path}{symbol}.parquet'
    data = pd.read_parquet(filepath)
    price_features = ['price_return', 'Price_Swing', 'MASignal']
    volume_features = ['volume_z_diff', 'volume_zscore30Days']
    volatility_features = ['volatility_diff', 'Volatility_30Days']
    
    for features, col_name in zip(
        [price_features, volume_features, volatility_features],
        ['price_score', 'volume_score', 'volatility_score']
    ):
        model = IsolationForest(contamination=contamination, random_state=42)
        model.fit(data[features])
        data[col_name] = model.decision_function(data[features])
    
    data['cum_score'] = (data['price_score'] + 
                         data['volume_score'] + 
                         data['volatility_score']) / 3
    data['is_anomaly'] = (data['cum_score'] < data['cum_score'].quantile(0.05)).astype(int)
    data.to_parquet(filepath, index=False)
    return data

## For all the 20 datas we have !

In [256]:
### Creating datasets for the top 20 companies 
watchlist = {
    "AAPL":  "Apple",
    "MSFT":  "Microsoft", 
    "NVDA":  "Nvidia",
    "GOOGL": "Alphabet (Google)",
    "AMD":  "AMD",
    "META":  "Meta (Facebook)",
    "TSLA":  "Tesla",
    "NFLX": "Netflix",
    "LLY":   "Eli Lilly",
    "AVGO":   "Broadcom",
    "MU":    "Micron Technology",
    "QCOM":   "Qualcomm",
    "UNH":   "UnitedHealth",
    "WMT":   "Walmart",
    "MA":    "Mastercard",
    "JNJ":   "Johnson & Johnson",
    "PG":    "Procter & Gamble",
    "HD":    "Home Depot",
    "ORCL":  "Oracle",
    "JPM": "JPMorgan Chase"
}

In [257]:
michelle = data_partition("AAPL")
michelle.head(5)

                       date   close  ...  cum_score  is_anomaly
0 2008-01-02 00:00:00+00:00  194.84  ...   0.140305           0
1 2008-01-03 00:00:00+00:00  194.93  ...   0.159989           0
2 2008-01-04 00:00:00+00:00  180.05  ...   0.065715           0
3 2008-01-07 00:00:00+00:00  177.64  ...   0.090104           0
4 2008-01-08 00:00:00+00:00  171.25  ...   0.097221           0

[5 rows x 29 columns]

In [258]:
for symbol in watchlist.keys():
    data_partition(symbol)
for symbol in watchlist.keys():
    iso_runner(symbol)
    print(f"{symbol} done")

AAPL done
MSFT done
NVDA done
GOOGL done
AMD done
META done
TSLA done
NFLX done
LLY done
AVGO done
MU done
QCOM done
UNH done
WMT done
MA done
JNJ done
PG done
HD done
ORCL done
JPM done

In [259]:
### Anamoly Count 
for symbol in watchlist.keys():
    data = pd.read_parquet(f'../updatedtop20datasets/{symbol}.parquet')
    counts = data['is_anomaly'].value_counts()
    print(f"{symbol}: {counts[1]/counts[0]} % anomalies")

AAPL: 0.05271529197909566 % anomalies
MSFT: 0.05271529197909566 % anomalies
NVDA: 0.05271529197909566 % anomalies
GOOGL: 0.05271529197909566 % anomalies
AMD: 0.05271529197909566 % anomalies
META: 0.052804295942720764 % anomalies
TSLA: 0.05282522996057819 % anomalies
NFLX: 0.05271529197909566 % anomalies
LLY: 0.05271529197909566 % anomalies
AVGO: 0.05274944015924359 % anomalies
MU: 0.05271529197909566 % anomalies
QCOM: 0.05271529197909566 % anomalies
UNH: 0.05271529197909566 % anomalies
WMT: 0.05271529197909566 % anomalies
MA: 0.05271529197909566 % anomalies
JNJ: 0.05271529197909566 % anomalies
PG: 0.05271529197909566 % anomalies
HD: 0.05271529197909566 % anomalies
ORCL: 0.05271529197909566 % anomalies
JPM: 0.05271529197909566 % anomalies