In [106]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest

### We will be using isolation forest to detect the anamolies

In [107]:
data = pd.read_parquet('../updatedtop20datasets/META.parquet')
data.head(5)

                       date    close  ...  volatility_diff  volume_z_diff
0 2012-05-18 00:00:00+00:00  38.2318  ...              0.0            0.0
1 2012-05-21 00:00:00+00:00  34.0300  ...              0.0            0.0
2 2012-05-22 00:00:00+00:00  31.0000  ...              0.0            0.0
3 2012-05-23 00:00:00+00:00  32.0000  ...              0.0            0.0
4 2012-05-24 00:00:00+00:00  33.0300  ...              0.0            0.0

[5 rows x 24 columns]

In [108]:
def data_partition(symbol):
    path = '../updatedtop20datasets/'
    filepath = f'{path}{symbol}.parquet'
    data = pd.read_parquet(filepath)
    columns =  ['price_return', 'volatility_diff', 'Volatility_30Days', 'Price_Swing', 'volume_z_diff', 'volume_zscore30Days', 'MASignal']
    scaler = StandardScaler()
    scaled_data = scaler.fit_transform(data[columns])
    scaled_data = pd.DataFrame(scaled_data, columns = columns, index = data['date'])
    scaled_data = scaled_data.reset_index()
    return scaled_data

In [122]:
def iso_runner(data,features, contamination = 0.05):
    iso = IsolationForest(contamination=contamination, random_state=42)
    iso.fit(data[features])
    scores = iso.decision_function(data[features])
    return scores

price_features = ['price_return', 'Price_Swing']
volume_features = ['volume_z_diff', 'volume_zscore30Days']
volatiltiy_features = ['volatility_diff', 'Volatility_30Days']
data['price_score'] = iso_runner(data, price_features)
data['volume_score'] = iso_runner(data, volume_features)
data['volatility_score'] = iso_runner(data, volatiltiy_features)
data['cum_score'] = (data['price_score'] + data['volume_score'] + data['volatility_score']) / 3
data['is_anomaly'] = (data['cum_score'] < data['cum_score'].quantile(0.05)).astype(int)
print(data['is_anomaly'].value_counts())

is_anomaly
0    3350
1     177
Name: count, dtype: int64

In [123]:
data.head(5)

                       date    close  ...  volatility_score  cum_score
0 2012-05-18 00:00:00+00:00  38.2318  ...          0.133157   0.044323
1 2012-05-21 00:00:00+00:00  34.0300  ...          0.133157   0.037627
2 2012-05-22 00:00:00+00:00  31.0000  ...          0.133157   0.051518
3 2012-05-23 00:00:00+00:00  32.0000  ...          0.133157   0.145207
4 2012-05-24 00:00:00+00:00  33.0300  ...          0.133157   0.132223

[5 rows x 29 columns]

In [125]:
peter = data[data['is_anomaly'] == 1]
peter.describe()

            close        high  ...  volatility_score   cum_score
count  177.000000  177.000000  ...        177.000000  177.000000
mean   302.341699  309.991605  ...          0.082209    0.018802
std    223.231902  227.290510  ...          0.111823    0.038807
min     19.870000   20.480000  ...         -0.144556   -0.123880
25%    146.010000  148.180000  ...         -0.018265    0.003974
50%    207.600000  211.751700  ...          0.112863    0.028744
75%    531.620000  547.430000  ...          0.177486    0.046387
max    773.440000  784.750000  ...          0.249996    0.059804

[8 rows x 27 columns]

In [126]:
parker = data[data['is_anomaly'] == 0]
parker.describe()

             close         high  ...  volatility_score    cum_score
count  3350.000000  3350.000000  ...       3350.000000  3350.000000
mean    229.251631   231.922122  ...          0.191472     0.157378
std     186.724106   188.839999  ...          0.066570     0.034578
min      17.729000    18.270000  ...         -0.146133     0.059944
25%      97.002500    97.927500  ...          0.181001     0.134919
50%     174.625000   176.655000  ...          0.214757     0.165590
75%     300.195000   304.900000  ...          0.233747     0.184660
max     790.000000   796.250000  ...          0.253422     0.212349

[8 rows x 27 columns]